### ISSUE TITLE
Error referencing 'FUTURENET' and 'SANDBOX' in SorobanClient.Networks

### ISSUE THREAD

**Issue by mauroepce** [stellar/js-soroban-client#104]
**Describe the bug**
I'm working on documentation for a project that uses `soroban-client` and I've encountered a problem with references to FUTURENET and SANDBOX in SorobanClient.Networks. When trying to reference these networks I get the following errors:

`Property 'FUTURENET' does not exist on type 'typeof Networks'`
`Property 'SANDBOX' does not exist on type 'typeof Networks'`

I've searched the documentation and repository but haven't found any mention of FUTURENET or SANDBOX that can help me solve this problem.

Have these constants been replaced or removed in a recent version? If so, what are the alternatives I should use instead? I would appreciate any help to resolve this issue.

**What version are you on?**
"0.8.0"

**To Reproduce**
This occurs even after successfully installing all the dependencies specified in the package.json of the packages and the root directory of the project.

**Expected behavior**
not having the error and successful reference

**Additional context**
"My dev environment includes Node.js v16.18.0, npm v8.19.2, on a MacOS Ventura. I'm using VSC as text editor."

**Comment by Shaptic** [comment]
It comes from an underlying dependency (`stellar-base@soroban`), defined here: [types/index.d.ts](https://github.com/stellar/js-stellar-base/blob/soroban/types/index.d.ts#L241-L247).

There was a bug in the 0.8.0 version of this package that used the wrong version of this dependency when starting a fresh project. Is this reference still missing in v0.8.1?

**Comment by mauroepce** [comment]
Perfect!. Thanks.
Now working without a problem with the v0.8.1 update.
