### ISSUE TITLE
Potentially mishandling expired entries in pre-flight

### ISSUE THREAD

**Issue by aristidesstaffieri** [stellar/js-soroban-client#116]
**Describe the bug**
I'm trying to simulate a tx with the following envelope - 
```
AAAAAgAAAACM6IR9GHiRoVVAO78JJNksy2fKDQNs2jBn8bacsRLcrAAAAGQAALDTAAAAQAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAAKAAAAEgAAAAEA1OFYsQR9ohuN4/lO01H0QR1gs0ydtgleqtNpia/V2AAAAA8AAAAEc3dhcAAAABIAAAAAAAAAAIzohH0YeJGhVUA7vwkk2SzLZ8oNA2zaMGfxtpyxEtysAAAAEgAAAAAAAAAA6BZdgAk/R2ZGwnrmk/TACHUraXX+fMDNz9uJ5e9/AJ0AAAASAAAAAfqr9cWsTR0VECjHorwcNTdllgfWPl95BDxSVggu+Z6lAAAAEgAAAAEN+Pv7pUMOoJ6rFclWu0CY3+3qzX6/IrjFY1zyC+VitQAAAAoAAAAAAAAAAAAAAAAAAAABAAAACgAAAAAAAAAAAAAAAAAAAAUAAAAKAAAAAAAAAAAAAAAAAAAABQAAAAoAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA
```
and `assembleTransaction` throws the following error

```
```
which I think is [from this line](https://github.com/stellar/js-soroban-client/blob/81dae3c03ad9b590c8c8583105a70d230e8d0f0c/src/transaction.ts#L35), because the preflight for this request returns no result key at all. Here is what I get from the simulate call - 

```
{
    "error": "HostError: Error(Storage, MissingValue)\nDebugInfo not available\n",
    "transactionData": "",
    "events": null,
    "minResourceFee": "0",
    "cost": {
        "cpuInsns": "0",
        "memBytes": "0"
    },
    "latestLedger": "163263"
}
```

**What version are you on?**
0.9.2

**To Reproduce**
You can run this dapp or just the code that from the `buildSwap` call.
https://github.com/stellar/soroban-react-atomic-swap/pull/4

**Expected behavior**
This was expired contract code. I'm not sure what the behavior should be, maybe if no results we can throw an error that lets the user know that they should restore the contract code. 

**Additional context**
Slack thread about it - https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1690827512838819

**Comment by aristidesstaffieri** [comment]
so there was a cli bug that made this confusing for me but in this case, the contract code was expired not the data.

**Comment by willemneal** [comment]
Also when using the CLI very verbose will print more logs.
E.g.
```
soroban --vv ...
```

**Comment by aristidesstaffieri** [comment]
> Also when using the CLI very verbose will print more logs. E.g.
> 
> ```
> soroban --vv ...
> ```

Thanks!

**Comment by aristidesstaffieri** [comment]
closing this, this works fine and my preflight response just had an error I didn't understand.
