### ISSUE TITLE
Add first class support to token operations

### ISSUE THREAD

**Issue by tomerweller** [stellar/js-soroban-client#13]
as defined in the token interface https://soroban.stellar.org/docs/reference/interfaces/token-interface

**Comment by leighmcculloch** [comment]
We should approach implementing this by implementing client binding generation for Javascript in the soroban-cli:
- https://github.com/stellar/soroban-cli/issues/8

Once we have client binding generation this SDK can embed as a first-class feature the generated client binding for the token contract whose interface is exported in the `soroban-token-spec` crate.

**Comment by tomerweller** [comment]
the token related operations should also have an expected footprint that can be codified in the sdk, rather than going through preflight

**Comment by Shaptic** [comment]
I believe this is closed by the new TypeScript bindings.
