### ISSUE TITLE
scValToNative not working

### ISSUE THREAD

**Issue by quankori** [stellar/js-soroban-client#148]
Currently, I am trying to decode scVal to its native format, but it is not working. I followed these steps:
1. I have a value scVal encoded as `AAAADwAAAAdkZXBvc2l0AA==` of type Sym.
2. I attempted to change it to type `SorobanClient.xdr.ScVal` using the following code:

```ts
const svcValue = SorobanClient.xdr.ScVal.scvSymbol(
      "AAAADwAAAAdkZXBvc2l0AA==",
);
```
The result is as follows:

```ts
ChildUnion {
  _switch: ChildEnum { name: 'scvString', value: 14 },
  _arm: 'str',
  _armType: String { _maxLength: 4294967295 },
  _value: 'AAAADwAAAAdkZXBvc2l0AA=='
}
```

3. However, when I use it with `scValToNative`, it returns the same old variable:

```ts
const scValDecode = await SorobanClient.scValToNative(svcValue);
console.log(scValDecode);
```

The result is `AAAADwAAAAdkZXBvc2l0AA==`. I attempted to decode it on website laboratory stellar, and the result was different: `ZGVwb3NpdA==`

**Comment by Shaptic** [comment]
that's because the `scvValue` itself is not correct: you need to specify the decoding

```js
const svcValue = SorobanClient.xdr.ScVal.fromXDR(
    "AAAADwAAAAdkZXBvc2l0AA==",
    "base64"
);
```

then it should be correct
