### ISSUE TITLE
1.0.0-beta.2 [AxiosError: Request failed with status code 405]

### ISSUE THREAD

**Issue by Spxc** [stellar/js-soroban-client#150]
**Describe the bug**
Trying to pull account data using `server.getAccount()` returns an 405 Axios error

**What version are you on?**
"soroban-client": "^1.0.0-beta.2"

**To Reproduce**
1. Create a new Node (or similar) project.
2. Install the client
3. Import the libraries and try to pull account data

**Expected behavior**
Returns: `[AxiosError: Request failed with status code 405]`

**Additional context**
Tried with the account: `GDIZOAHWITGPTOCKF3S6TPFVSEEBTH32MAN3JYOYXDZLLS5K6IGYMRQ7` and the server URL: `https://horizon-futurenet.stellar.org`

**Full test code***
```
const SorobanClient = require('soroban-client')
const server = new SorobanClient.Server('https://horizon-futurenet.stellar.org')

server.getAccount(account).then((data) => { 
     return data
})
 .catch(error => {
     return error
})

**Comment by Spxc** [comment]
[Repo with working code & example](https://github.com/Spxc/ReactNative_Stellar_Soroban_Wallet)

**Comment by Shaptic** [comment]
that's because you're using the RPC client with Horizon: you should either use stellar-sdk or use an RPC endpoint
