### ISSUE TITLE
js-soroban-sdk: getEvents method support

### ISSUE THREAD

**Issue by paulbellamy** [stellar/js-soroban-client#2]
With the decision in https://github.com/stellar/go/issues/4676 to not do push streaming, there is a risk that people will implement their own polling in the clients. This would likely be done in a rudimentary way, which would be unreliable, and cause us excessive load on soroban-rpc. We could add a `streamEvents` method in the js sdk, which would show a better way to do the polling (predict next block, and try w backoff/jitter, etc). If people use this 🤞 , it could reduce load on soroban-rpc.

**Comment by jcx120** [comment]
-Add getEvent method to SDK
 - work in browser, node.js context
 - include filtering 
-  (separate story) Add streaming endpoint
