### ISSUE TITLE
js-soroban-sdk: Write docs, and get them building for this repo.

### ISSUE THREAD

**Issue by paulbellamy** [stellar/js-soroban-client#20]
It would be good to have js-docs written/building/published for this client library. @tomerweller did some work on getting them building, but afaik none are written so far.

Primarily https://github.com/stellar/js-soroban-client/blob/main/src/server.ts, would be good to have some docs. Could be based on the soroban-rpc api docs.

Acceptance Criteria:
Document all the source code in `js-soroban-client/src`, and add auto-generating documentation from source code.

**Comment by jcx120** [comment]
Doc framework is in place, first time publish. Follow formatting for js docs, javascript sdk
Review: tyler, discord community
Separate: document examples and json api.
