### ISSUE TITLE
Does not work with playgrounds like runkit

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/js-soroban-client#23]
**Describe the bug**
Importing into playgrounds like runkit result in errors.
<img width="906" alt="Screenshot 2022-11-09 at 10 11 32 AM" src="https://user-images.githubusercontent.com/351529/200908552-6bdd29e1-5ad3-4942-a6fa-4fb76a524975.png">

**What version are you on?**
`main`

**To Reproduce**
https://runkit.com/leighmcculloch/stellar--js-soroban-sdk--issue-23

**Expected behavior**
Not error.

**Comment by Shaptic** [comment]
This is no longer true: https://runkit.com/61833274873f8c000b42e673/646d2f15ed3cd000081ab34b.
