### ISSUE TITLE
docs: Emit SorobanRpc.*Response types into jsdoc

### ISSUE THREAD

**Issue by paulbellamy** [stellar/js-soroban-client#28]
Currently the comments there get stripped out by the typescript compilation step, so they are not included in the jsdoc.
We should emit them so we can link to them from the `server.ts` docs.

Follow-up from https://github.com/stellar/js-soroban-client/pull/27

**Comment by Shaptic** [comment]
I think this is complete as of https://github.com/stellar/js-soroban-client/pull/88 and https://github.com/stellar/js-soroban-client/pull/87.
