### ISSUE TITLE
Importing this library from a plain javascript project depends on `tslib`

### ISSUE THREAD

**Issue by paulbellamy** [stellar/js-soroban-client#37]
@accordeiro created a new javascript project from scratch. He installed `soroban-client`, and did `npm install`.

His `index.js` was:
```js
var SorobanClient = require('soroban-client');
var server = new SorobanClient.Server('http://localhost:8000/soroban/rpc');

// get the sequence number for an account
server.getAccount(
  'GASOCNHNNLYFNMDJYQ3XFMI7BYHIOCFW3GJEOWRPEGK2TDPGTG2E5EDW'
).then(function(r){ console.log(r); });
```

But when trying to run it, the error was:
```
> sns-sdk@1.0.0 start
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'tslib'
...
```

`npm install tslib` resolved the issue, but this shouldn't be a requirement for users.

From a quick google it looks like we should set `importHelpers: false` in this library's tsconfig.

Note: This might also affect `js-stellar-sdk`?

**Comment by accordeiro** [comment]
Also should probably change line `2` in the example to:

```js
var server = new SorobanClient.Server('http://localhost:8000/soroban/rpc', {allowHttp:true});
```

Since it rejects non-https RPC servers by default. Happy to also file a separate issue for this one, let me know.

**Comment by Shaptic** [comment]
This is no longer true.
