### ISSUE TITLE
When auth is null for `prepareTransaction` the server response fails

### ISSUE THREAD

**Issue by tyvdh** [stellar/js-soroban-client#55]
I'm calling a function that doesn't return anything and doesn't require any auth so the `auth` is `null` in the response to the `prepareTransaction` call.

<img width="424" alt="Screenshot 2023-02-28 at 11 30 52 AM" src="https://user-images.githubusercontent.com/4383610/221946752-0b4cd58a-2273-4802-b0a8-d3cccc538e32.png">

This results in a 
```
TypeError: Cannot read properties of null (reading 'map')
```

**Comment by tyvdh** [comment]
It would seem in my case I don't need to call `prepareTransaction`. This should be more clear. Still, not a critical error in my case.

**Comment by Shaptic** [comment]
I think this is resolved as part of #103 where type definitions note that `SorobanRpc.SimulateHostFunctionResult.auth` may be missing. Please reopen if you see it happen again after the futurenet ugprade!
