### ISSUE TITLE
add support for smart contract diagnostic events

### ISSUE THREAD

**Issue by tsachiherman** [stellar/js-soroban-client#59]
### What
add support for smart contract debug events

### How

As a result, the code calling soroban-rpc's simulateTransaction and getEvents should be updated to match the changes at https://github.com/stellar/soroban-tools/issues/473 and https://github.com/stellar/soroban-tools/issues/475

TODO : we need a bit deeper analysis so we can better estimate time efforts. example : how many objects would be changed, which unit tests are going to be affected.

### Epic
https://github.com/stellar/soroban-tools/issues/471

**Comment by 2opremio** [comment]
As a result, the code calling soroban-rpc's `simulateTransaction` and `getEvents` should be updated to match the changes at https://github.com/stellar/soroban-tools/issues/473 and https://github.com/stellar/soroban-tools/issues/475
