### ISSUE TITLE
js-soroban-client: add support for fees

### ISSUE THREAD

**Issue by tsachiherman** [stellar/js-soroban-client#76]
### What ?

txnbuilder and prepareTransaction need changes to support the fee model, because they need to set which resources the txn will use

### Epic

https://github.com/stellar/soroban-tools/issues/519

**Comment by sreuland** [comment]
@tsachiherman , is there an example in go or any other sdk's of how a client is expected to set resources/fees when building an invokehostfn txn? Or a link to docs/cap with some details on the expectations, thanks!

**Comment by sreuland** [comment]
> @tsachiherman , is there an example in go or any other sdk's of how a client is expected to set resources/fees when building an invokehostfn txn? Or a link to docs/cap with some details on the expectations, thanks!

thanks for discussion, am able to proceed on related changes in sdk. most of the changes for handling the new simulation response with SorbanTransactionData will be in the `assembleTransaction` method.

**Comment by sreuland** [comment]
PR - https://github.com/stellar/js-soroban-client/pull/77

**Comment by sreuland** [comment]
moving this to blocked as dev and unit test complete, but tests are failing due a strange issue with the js xdr generation, investigating further on pr - https://github.com/stellar/js-soroban-client/pull/77#discussion_r1190609852

**Comment by sreuland** [comment]
found a workaround and moved pr back to review - https://github.com/stellar/js-soroban-client/pull/77
