### ISSUE TITLE
Could not unmarshal transaction

### ISSUE THREAD

**Issue by lmorgan824** [stellar/js-soroban-client#84]
**Describe the bug**
When trying to simulate a transaction with server.simulateTransaction(), getting error "Could not unmarshal transaction"

**What version are you on?**
js-soroban-client 0.6.1  soroban-tools 0.7.0

**To Reproduce**
1. Go to github.com/blocktimefinancial/option/pxpump
2. Open pxpump.js
3. Scroll down to line 135
4. See error message below from the execution results.

**Expected behavior**
.simulateTransaction should return cost, results, error, and latestLedger

**Additional context**
Output from pxpump.js application
Creating contract transaction for cd0ca2f721d91df334b79fb1e043920919ed0c6b09f930af5048a50930fb7f44
Tx XDR: AAAAAgAAAADzwQ11keCAXiGbzzenrJCF67uR4i8TRh6rq10fRyygkwAAAGQAACitAAAQOQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGAAAAAEAAAAAAAAABgAAAA0AAAAgzQyi9yHZHfM0t5+x4EOSCRntDGsJ+TCvUEilCTD7f0QAAAAPAAAABnVwZGF0ZQAAAAAACgAAAAAAAAAAAAAAAAAAAAEAAAAKAAAAAAAAAAAAAAAAAACjaAAAAAoAAAAAAAAAAAAAAYg1aIvAAAAACgAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAA=
Simulating transaction for cd0ca2f721d91df334b79fb1e043920919ed0c6b09f930af5048a50930fb7f44
Signing with secret: SCIGOGUPFOZSEBVZBEF3BJL6SZGVSFYANQ6BZE6PTTQ7S4YXYDPY4JHL
cost: { cpuInsns: '0', memBytes: '0' }
results: undefined
error: Could not unmarshal transaction
latestLedger: 0
Preparing transaction for cd0ca2f721d91df334b79fb1e043920919ed0c6b09f930af5048a50930fb7f44
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Could not unmarshal transaction".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by sreuland** [comment]
this 0.6.1 release is meant for the upcoming Preview9 release, it's not backwards compatible with cli/rpc from soroban-tools 0.7.0. It will need to be used with new rpc/cli from upcoming 0.8.0 release of soroban-tools. For Preview8, should stay at 0.5.1 release of js-soroban-client and rpc and cli from soroban-tools 0.7.0.

**Comment by Spxc** [comment]
@lmorgan824 Did you ever figure this out? Getting the same error when trying to simulate a tx.
"Could not unmarshal", get this when loading accounts as well (randomly)

**Comment by gangov** [comment]
same here, following the soroban quests in gitpods

**Comment by Shaptic** [comment]
Can anyone confirm or deny that this is still occurring?

**Comment by Spxc** [comment]
@Shaptic Still occuring

**Comment by Shaptic** [comment]
@Spxc can you share the following?
 - a specific transaction envelope that is failing with this error
 - your soroban-client version
 - the RPC endpoint you are using

**Comment by Spxc** [comment]
> @Spxc can you share the following?
> 
> * a specific transaction envelope that is failing with this error
> * your soroban-client version
> * the RPC endpoint you are using

- Not related to any tx evelope (get these errors calling `*.getAccount()`)
- `soroban-client": "^0.8.1` - JS SDK
- Guess that would the `/account` endpoint, as we're not able to get past fetching the account.

**Comment by Shaptic** [comment]
Can you try upgrading to v0.9.2? This is the earliest supported version for the current futurenet deployment (Preview 10): https://soroban.stellar.org/docs/reference/releases#preview-10-july-13-2023. It would be best to upgrade to the latest version ([v0.11.0](https://github.com/stellar/js-soroban-client/releases/v0.11.0), also compatible), but that's the minimum.

**Comment by lmorgan824** [comment]
Fixed with upgrade
